### ISSUE TITLE
Pair multiple images with a common label

### ISSUE THREAD

**Issue by naga-karthik** [ivadomed/templates#2]
It was pointed out by @valosekj that upon using this command: 

```python
python bids_to_msd_dataset_conversion.py --path-data test_dataset --path-out test_dataset_msd --split 0.6 0.2 0.2 --label-suffix _gmseg-manual_crop --include-contrasts T1w T2star --common-label-contrast T1w
```

the expected behaviour is that the T1w label should be used with all the included contrasts. Earlier, this feature was only possible when multiple contrasts were grouped by using `--group-by-contrasts`.

**Comment by naga-karthik** [comment]
This is a great suggestion and this feature has now been implemented in e90869d6b88ede2624c581bf8796912e15b9f6b5

Command used: 

```python
python bids_to_msd_dataset_conversion.py --path-data ~/datasets/test_dataset --path-out ../ --split 0.6 0.2 0.2 --label-suffix _gmseg-manual_crop --include-contrasts T1w T2star --common-label-contrast T1w
```

How it looks in the output json file: 
<img width="1103" alt="Screen Shot 2023-03-04 at 1 16 15 PM" src="https://user-images.githubusercontent.com/53445351/222922251-3c02cf4e-977d-42da-9c57-6073c09b1391.png">

@valosekj please pull the latest version of the branch and you can test it out yourself!

**Comment by valosekj** [comment]
Thank you @naga-karthik for the quick implementation of this feature! Tested and it is working as expected!

**Comment by naga-karthik** [comment]
Perfect! Closing the issue then!
