### ISSUE TITLE
For script flags, replace "_" by "-"

### ISSUE THREAD

**Issue by jcohenadad** [ivadomed/templates#4]
https://github.com/ivadomed/templates/blob/5cf865256bd962bfba3a5cad79deffe0a5a72ace/convert_ivadomed_splits_nnunet.py#L69-L76

**Comment by naga-karthik** [comment]
Thank you for pointing this out! This has been fixed in commit 00bf738d1e85cea33ab70eeea1e160e88ffe8e85.
